### ISSUE TITLE
Does not work if token and no query specified

### ISSUE THREAD

**Issue by simsea** [imgix/imgix-objc#3]
in IGXClient  - (NSString *)queryStringWithPath:(NSString *)path

needs to be: 

```
    NSString *input;
    if (nil != query && 0 != query.length)
        input = [[NSString alloc] initWithFormat:@"%@%@?%@", self.token, path, query];
    else
        input = [[NSString alloc] initWithFormat:@"%@%@", self.token, path];
```

instead of 
        NSString *input = [[NSString alloc] initWithFormat:@"%@%@?%@", self.token, path, query];

In the existing code, if query is empty, it adds a '?' at the end of the encoder input string which leads to the wrong encoded string.

**Comment by paulstraw** [comment]
Hey @simsea, should be all better as of #7. Let me know if you're still seeing any issues around this!
