### ISSUE TITLE
imgix org transfer

### ISSUE THREAD

**Issue by paulstraw** [imgix/imgix-objc#4]
Hey @soffes, just wanted to open an issue for tracking this on my end. 👋

**Comment by soffes** [comment]
Going to transfer to you since I don't have permission to transfer to imgix.

**Comment by soffes** [comment]
Done!

**Comment by paulstraw** [comment]
Hmm, it doesn't seem to have actually transferred, unfortunately. It might be easier to just add me as an admin collaborator, and then I can directly transfer it to the imgix org.

**Comment by soffes** [comment]
Says you need to approve it. Guessing you got an email.

**Comment by paulstraw** [comment]
Oh, oops. Sorry about that, all set. I'm so lost now that I don't have Mailbox anymore. 😞
