### ISSUE TITLE
URL signing not working

### ISSUE THREAD

**Issue by maxperry** [imgix/imgix-objc#5]
Looks like the URL signing has changed recently. In fact, the Iris library for Swift works instead. However, it cannot be imported "as-is" in an Objective-C project because there is no support for type structures.
Therefore a fix would be really appreciated.

**Comment by paulstraw** [comment]
Hmm, URL signing hasn't been changed in our backend lately. Can you provide an example URL and/or code where you're seeing this?

**Comment by maxperry** [comment]
Could the Objective-C library not be calculating the signature correctly? Sorry but I cannot provide a URL due to sensitive data. The involved method is `URLWithPath:`

**Comment by paulstraw** [comment]
There are tests that validate signature generation, and they're still passing. I'll look into this more, but can you tell me whether you've specified any additional options on the instance of `IGXClient` you're using to generate the URLs?

**Comment by maxperry** [comment]
In fact, below is the URL being tested under the tests, but just like in the case of my images it's returning unauthorized.
https://nothingmagical.imgix.net/sam.jpg?s=6925569b28658d7a7299f06d520a22dd
I didn't set any options either.

**Comment by paulstraw** [comment]
Hmm. I'll dig into this soon.

**Comment by paulstraw** [comment]
Hey @maxperry, this should be fixed in master. Can you give it a shot and let me know how it works for you?

**Comment by maxperry** [comment]
It works fine now :) Thank you very much for fixing this!

**Comment by paulstraw** [comment]
Very cool. No problem!
